### ISSUE TITLE
M1 MAC - Pyaudio problems - Could not import the PyAudio C module 'pyaudio._portaudio'.

### ISSUE THREAD

**Issue by adamSplendex** [Frikallo/MISST#12]
Hello!

I have an M1MAX Macbook Pro with everything installed as a prerequisite. 

I came across this and wanted to give it a try. The installation itself was problematic but i was able to fix the dependency issues with torchaudio and so.

Finally the app is built but i receive this after the `python MISSTapp.py` command: 

`(MISSTvenv) [~/dvlpmnt/MISST/MISST] python MISSTapp.py     
Could not import the PyAudio C module 'pyaudio._portaudio'.
Traceback (most recent call last):
  File "/Users/erekhron/dvlpmnt/MISST/MISST/MISSTapp.py", line 25, in <module>
    from MISSThelpers import MISSTconsole, MISSThelpers
  File "/Users/erekhron/dvlpmnt/MISST/MISST/MISSThelpers.py", line 19, in <module>
    from MISSTplayer import MISSTplayer
  File "/Users/erekhron/dvlpmnt/MISST/MISST/MISSTplayer.py", line 8, in <module>
    import pyaudio
  File "/Users/erekhron/miniconda3/envs/MISSTvenv/lib/python3.12/site-packages/pyaudio/__init__.py", line 111, in <module>
    import pyaudio._portaudio as pa
ImportError: dlopen(/Users/erekhron/miniconda3/envs/MISSTvenv/lib/python3.12/site-packages/pyaudio/_portaudio.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace (_PaMacCore_SetupChannelMap)
(MISSTvenv) [~/dvlpmnt/MISST/MISST]`
                                                                                                                            
After this i spent 3 hours to try to fix it but none of the google searched helped, i reinstalled stuff, reinstalled my whole python env etc.

Anything I could do? :(

**Comment by Frikallo** [comment]
Hi, so sorry for the inconvenience, unfortunately MISST is no longer being maintained and was never built with mac compatibility in mind. If you do find a fix feel free to make a pull request and ill be happy to merge it but for the time being, there is no official support for MacOS and MISST is not under any active development.
