### ISSUE TITLE
build on linux how to

### ISSUE THREAD

**Issue by sdfsfsfwrt** [Frikallo/MISST#6]
hello 
can you help me to build it under linux

**Comment by Frikallo** [comment]
as far as i’m aware MISST should be functional on linux by installing requirements with 'pip install requirements.txt' followed by 'python3.9 MISSTapp.py' while in the MISST directory, unfortunately I haven't built any linux binaries to date but expect support soon, if you run into any errors building on linux from python please attach your traceback.

**Comment by Frikallo** [comment]
did you manage to get it working?
