### ISSUE TITLE
How to use Finetuned model "htdemucs_ft"

### ISSUE THREAD

**Issue by zorikfx** [Frikallo/MISST#7]
There exists the finetuned model 'htdemucs_ft', does yours have this feature? If not, how do I go about getting it on MISST?

**Comment by Frikallo** [comment]
Unfortunately model selection is not yet directly supported in MISST but is actively under development and will release with 3.1.0. For now, if you'd like to change the model you'll have to go into MISSTpreprocess.py and change anything stating the model as mdx to ht_demucs and update the files within the ./Pretrained folder, check the official demucs repo for the correct config for htdemucs. I have tried doing this but my attempts were unsuccessful, if you find a workaround consider creating a PR! Let me know if you have any other questions regarding the MISST code base.

**Comment by Frikallo** [comment]
You can now choose a specific demucs model for preprocessing in MISST by accessing the settings panel and navigating to the 'advanced' tab. From there, you can select your preferred model, and finalize the setup by clicking the "download and save" button.
